### ISSUE TITLE
analytics script tag is duplicated after using the plugin

### ISSUE THREAD

**Issue by darkopetreski** [chrisvfritz/prerender-spa-plugin#102] opened 2017-09-10 11:20 UTC
When using google analytics script code, the prerendered html in the head looks like:

```html
<script async="" src="https://www.google-analytics.com/analytics.js"></script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
```
When the page is opened in a browser, it keeps the generated script tag, and the analytics code then when executed it adds another script tag, ending with double script tag

```html
<script async="" src="https://www.google-analytics.com/analytics.js"></script>
<script async="" src="https://www.google-analytics.com/analytics.js"></script>
```

**Comment by OlzhasAlexandrov** [comment] 2017-09-12 14:40
Possible duplicate of #82

**Comment by drewlustro** [comment] 2017-09-26 10:11
### Closing due to dupe.

This is a related to / dupe of #103, #105, and loosely #107. 

---

Your endpoints are rendering and capturing the HTML verbatim. If Vue injects more on dynamic mount, it will be duplicate `<script> .. </script>` markup.

Use `postProcessHtml` to sanitize your HTML into one unique set of CSS or JSS markup.

---

**From the README doc:**

```jsx
// Manually transform the HTML for each page after prerendering,
// for example to set the page title and metadata in edge cases
// where you cannot handle this via your routing solution.
//
// The function's context argument contains two properties:
//
// - html :: the resulting HTML after prerendering)
// - route :: the route currently being processed
//            e.g. "/", "/about", or "/contact")
//
// Whatever is returned will be printed to the prerendered file.
postProcessHtml: function (context) {
  var titles = {
    '/': 'Home',
    '/about': 'Our Story',
    '/contact': 'Contact Us'
  }
  return context.html.replace(
    // strip all script tags
    /<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/i,
    '' 
  )
}
```

**Closed by drewlustro** 2017-09-26 10:11 UTC

**Comment by edarioq** [comment] 2018-06-30 22:20
@drewlustro Doesn't this remove all script tags generated in the final HTML?

**Comment by DamageESP** [comment] 2018-07-20 11:02
All of my (async) scripts get duplicated upon prerendering. This screws all dynamically rendered content (external iframes, like Repuso and Tawk.to in my case, don't even render at all).

I'm surprised this is not addressed, and is deflected as "out of the scope" of the plugin or [vague solutions](https://github.com/chrisvfritz/prerender-spa-plugin/issues/102#issuecomment-332152372) are provided.

Hope we can shed some light into this and get a consistent solution.

**Comment by zheeeng** [comment] 2018-09-06 19:18
+1 need a general solution for handling this problem.

**Comment by DamageESP** [comment] 2018-09-06 19:48
I ended up rendering all my stuff without any scripts and manually adding them after the render...

**Comment by poljeff** [comment] 2018-10-30 17:10
> I ended up rendering all my stuff without any scripts and manually adding them after the render...

para cada vista prerendereada?

**Comment by bigsee** [comment] 2019-05-01 10:57
+100 for this. Renders the plugin almost useless for many common use cases, I'm afraid (pun intended). Spent so much time hacking around trying to remove and replace <script> tags and still not working since there are script tags with dynamic elements generated by the Google Maps packages and API - surely the issue of dupes should be handled by the plugin somehow...

**Comment by DamageESP** [comment] 2019-05-01 11:12
In case this is useful, here's what I've been doing to circunvent this:

I created a file called `extraScripts.js`, which exports a string with all the extra content I want to be added to each and every rendered page:


extraScripts.js
=========
```javascript
module.exports = `
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX-X"></script>
<script type="text/javascript" src="https://repuso.com/widgets/grid.js" async></script>
<script type="text/javascript">
      var Tawk_API = Tawk_API || {},
        Tawk_LoadStart = new Date();
      (function () {
        var s1 = document.createElement("script"),
          s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/xxxxxx/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
      })();
</script>
<script>
      window.dataLayer = window.dataLayer || []
      function gtag() {
        dataLayer.push(arguments)
      }
      gtag('js', new Date())
      gtag('config', 'UA-XXXXXXX-X')
</script>
`
```

Then, in `webpack.prod.conf.js`:

webpack.prod.conf.js
=========
```javascript
const extraScripts = require('./extraScripts.js')
/* ... */

new PrerenderSPAPlugin({
  // Required - The path to the webpack-outputted app to prerender.
  staticDir: path.join(__dirname, '../dist'),
  // Required - Routes to render.
  routes: ['route1', 'route2'],
  postProcess (context) {
    const bodyEnd = context.html.indexOf('</body>')
    context.html = context.html.substr(0, bodyEnd) + extraScripts + context.html.substr(bodyEnd)

    return context
  }
})
/* ... */

```

This produces the desired output for me. Of course you can modify the `postProcess` function to insert whatever string in whatever position in your final HTML.

**Comment by alexsonnay** [comment] 2020-12-01 07:50
Awesome. It's the only solution available on the internet for this issue ! Thanks @DamageESP

**Comment by loeffel-io** [comment] 2021-11-08 14:51
> In case this is useful, here's what I've been doing to circunvent this:
> 
> I created a file called `extraScripts.js`, which exports a string with all the extra content I want to be added to each and every rendered page:
> 
> # extraScripts.js
> ```js
> module.exports = `
> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX-X"></script>
> <script type="text/javascript" src="https://repuso.com/widgets/grid.js" async></script>
> <script type="text/javascript">
>       var Tawk_API = Tawk_API || {},
>         Tawk_LoadStart = new Date();
>       (function () {
>         var s1 = document.createElement("script"),
>           s0 = document.getElementsByTagName("script")[0];
>         s1.async = true;
>         s1.src = 'https://embed.tawk.to/xxxxxx/default';
>         s1.charset = 'UTF-8';
>         s1.setAttribute('crossorigin', '*');
>         s0.parentNode.insertBefore(s1, s0);
>       })();
> </script>
> <script>
>       window.dataLayer = window.dataLayer || []
>       function gtag() {
>         dataLayer.push(arguments)
>       }
>       gtag('js', new Date())
>       gtag('config', 'UA-XXXXXXX-X')
> </script>
> `
> ```
> 
> Then, in `webpack.prod.conf.js`:
> 
> # webpack.prod.conf.js
> ```js
> const extraScripts = require('./extraScripts.js')
> /* ... */
> 
> new PrerenderSPAPlugin({
>   // Required - The path to the webpack-outputted app to prerender.
>   staticDir: path.join(__dirname, '../dist'),
>   // Required - Routes to render.
>   routes: ['route1', 'route2'],
>   postProcess (context) {
>     const bodyEnd = context.html.indexOf('</body>')
>     context.html = context.html.substr(0, bodyEnd) + extraScripts + context.html.substr(bodyEnd)
> 
>     return context
>   }
> })
> /* ... */
> ```
> 
> This produces the desired output for me. Of course you can modify the `postProcess` function to insert whatever string in whatever position in your final HTML.

So your scripts are then only available on prerendered pages?

**Comment by loeffel-io** [comment] 2021-11-13 13:54
Just solved it by using the inject 

```ts
// main.ts

// scripts
import {cookieConsentScript, cookieConsentStyle, googleAnalyticsScript, scripts} from './script';

if (!window.hasOwnProperty('__PRERENDER_INJECTED')) {
  document.head.append(googleAnalyticsScript);
  document.head.appendChild(cookieConsentScript);
  document.head.appendChild(cookieConsentStyle);
  scripts();
}
```

```js
// script.js

/**
 * External
 */
const googleAnalyticsScript = document.createElement('script');
googleAnalyticsScript.setAttribute('async', '');
googleAnalyticsScript.setAttribute('src', 'https://www.googletagmanager.com/gtag/js?id=UA-212200539-2');

const cookieConsentScript = document.createElement('script');
cookieConsentScript.setAttribute('src', 'https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.js');

const cookieConsentStyle = document.createElement('link');
cookieConsentStyle.setAttribute('href', 'https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.css');
cookieConsentStyle.setAttribute('rel', 'stylesheet');
cookieConsentStyle.setAttribute('type', 'text/css');

function scripts() {
  /**
   * Google Analytics
   */
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }

  gtag('js', new Date());
  gtag('config', 'UA-212200539-2');

  /**
   * Hotjar
   */
  (function(h, o, t, j, a, r) {
    h.hj = h.hj || function() {
      (h.hj.q = h.hj.q || []).push(arguments);
    };
    h._hjSettings = {hjid: 2688814, hjsv: 6};
    a = o.getElementsByTagName('head')[0];
    r = o.createElement('script');
    r.async = 1;
    r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
    a.appendChild(r);
  })(window, document, 'https://static.hotjar.com/c/hotjar-', '.js?sv=');

  /**
   * Cookie consent
   */
  window.addEventListener('load', function() {
    window.wpcc.init({
      'border': 'normal',
      'corners': 'small',
      'colors': {
        'popup': {
          'background': '#202128',
          'text': '#d5d6e0',
          'border': '#393b49',
        }, 'button': {'background': '#ff4655', 'text': '#ffffff'},
      },
      'position': 'bottom-right',
      'padding': 'small',
      'margin': 'small',
      'transparency': '5',
      'content': {'href': 'https://fielt.io/privacy'},
    });
  });
}

export {
  googleAnalyticsScript,
  cookieConsentScript,
  cookieConsentStyle,
  scripts,
};
```
