### ISSUE TITLE
Why script tag and styles are rendered twice?

### ISSUE THREAD

**Issue by iamdubx** [chrisvfritz/prerender-spa-plugin#105] opened 2017-09-19 14:28 UTC
I have duplicates in rendered index.html. 

```
<style type="text/css">img{width:100%}#app{font-family:Avenir,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-align:center;color:#2c3e50;margin-top:60px}h1,h2{font-weight:400}ul{list-style-type:none;padding:0}li{display:inline-block;margin:0 10px}a{color:#42b983}</style>
<style type="text/css">img{width:100%}#app{font-family:Avenir,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-align:center;color:#2c3e50;margin-top:60px}h1,h2{font-weight:400}ul{list-style-type:none;padding:0}li{display:inline-block;margin:0 10px}a{color:#42b983}</style>
```

```
<script src="build.js"></script>
  <script type="text/javascript" src="build.js"></script>
```

Please provide a solution or example with webpack configuration.

**Comment by ricricucit** [comment] 2017-09-25 15:04
this is most probably a misconfiguration of webpack (probably a misconfiguration of [https://github.com/jantimon/html-webpack-plugin](html-webpack-plugin))

**Comment by ricricucit** [comment] 2017-09-25 15:05
or... duplicate of issue #103

**Comment by drewlustro** [comment] 2017-09-26 10:03
Related to #103 and #107.

It's anticipated behavior. Closing due to duplicate.

**Closed by drewlustro** 2017-09-26 10:03 UTC
